export const SET_SESSION = 'SET_SESSION';
export const GET_TIME_ENTRIES_REQUEST = 'GET_TIME_ENTRIES_REQUEST';
export const GET_TIME_ENTRIES_RESPONSE = 'GET_TIME_ENTRIES_RESPONSE';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_RESPONSE = 'GET_USER_RESPONSE';
